# Generated by Django 6.0.4 on 2026-04-29 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('data_added', models.DateTimeField(default=datetime.datetime(2026, 4, 29, 19, 12, 15, 24368, tzinfo=datetime.timezone.utc))),
                ('studentImage', models.ImageField(upload_to='Students/')),
                ('Sem', models.CharField(choices=[('I', '1st SEM'), ('II', '2nd SEM'), ('III', '3rd SEM'), ('IV', '4th SEM'), ('V', '5th SEM'), ('VI', '6th SEM')], max_length=3)),
                ('sub', models.CharField(choices=[('Math', 'Mathmatics'), ('Py', 'Python'), ('cpp', 'C_Plus_Plus'), ('JS', 'Javascript'), ('DJ', 'Django'), ('CS', 'CyberSecurity'), ('DS', 'DataScience'), ('CC', 'CloudComputing')], max_length=4)),
            ],
        ),
    ]
